#seata:
#  enabled: true
#  application-id: zjjhyzd-spring-boot
#  tx-service-group: tx_group
#  enable-auto-data-source-proxy: false   #一定要是false
#  service:
#    vgroup-mapping:
#      tx_group: default  #key与上面的tx-service-group的值对应
#    grouplist:
#      default: 127.0.0.1:8091 #seata-server地址仅file注册中心需要
#  config:
#    type: file
#  registry:
#    type: file
wx:
  miniapp:
    configs:
      - appid: wxf7d96f5ce4da0c9b
        secret: 1051a8ba4f885f11fe8145602b17c989
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
aliyun:
  oss:
    enable: false
  sms:
    enable: false
youzan:
  enable: false
upload:
  domain: http://www.baidu.com
  base-path: F:/ENV
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  application:
    name: zjjhyzd-spring-boot
  datasource:
    druid:
      stat-view-servlet:
        enabled: false
        loginUsername: admin
        loginPassword: 123456
    url: jdbc:mysql://localhost:3306/${spring.application.name}?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    dynamic:
#      druid: #以下是支持的全局默认值
#        max-active: 20
#        time-between-eviction-runs-millis: 30000
#        connection-properties: druid.stat.mergeSql=true
#        filters: stat,wall # 注意这个值和druid原生不一致，默认启动了stat,wall
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
#      seata: true    #开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
#      seata-mode: AT #支持XA及AT模式,默认AT
#      datasource:
#        master:
#          url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&useSSL=false&characterEncoding=utf8
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
#        slave_1:
#          url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&useSSL=false&characterEncoding=utf8
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: ASSIGN_ID
logging:
  level:
    com.zjjhyzd.springboot: DEBUG
springfox:
  documentation:
    swagger-ui:
      enabled: false
knife4j:
  enable: true